In [1]:
%%bash

# check cuda, cudnn, tensorflow

nvidia-smi
nvcc -V
python -c "import tensorflow as tf;print('tensorflow version: ',tf.__version__)"

Mon May 15 08:31:53 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.104      Driver Version: 528.78       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0  On |                  N/A |
| N/A   51C    P8    12W /  93W |    197MiB /  6144MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

#### Make sure you are working under `training_demo/`

## Preparing the dataset

Copy `train.record` and `valid.record` to `training_demo/annotations/`.

## Training the model

In [4]:
!python model_main_tf2.py --model_dir=models/my_ssd_resnet50_v1_fpn --pipeline_config_path=models/my_ssd_resnet50_v1_fpn/pipeline.config

2023-05-03 10:50:53.359553: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:923] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-05-03 10:50:53.366796: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:923] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-05-03 10:50:53.367093: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:923] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-05-03 10:50:53.367662: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the app

2023-05-03 10:51:05.593490: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
/usr/local/lib/python3.6/dist-packages/keras/backend.py:401: UserWarning: `tf.keras.backend.set_learning_phase` is deprecated and will be removed after 2020-10-11. To update it, simply pass a True/False value to the `training` argument of the `__call__` method of your layer or model.
  warnings.warn('`tf.keras.backend.set_learning_phase` is deprecated and '
I0503 10:51:10.465590 140593732773632 api.py:446] feature_map_spatial_dims: [(32, 32), (16, 16), (8, 8), (4, 4), (2, 2)]
I0503 10:51:18.153299 140593732773632 api.py:446] feature_map_spatial_dims: [(32, 32), (16, 16), (8, 8), (4, 4), (2, 2)]
2023-05-03 10:51:22.800698: I tensorflow/stream_executor/cuda/cuda_dnn.cc:369] Loaded cuDNN version 8100
2023-05-03 10:51:24.805587: I tensorflow/stream_executor/cuda/cuda_blas.cc:1760] TensorFloat-32 will be used for the matrix multiplicatio

INFO:tensorflow:Step 100 per-step time 0.490s
I0503 10:52:17.144510 140603801323328 model_lib_v2.py:707] Step 100 per-step time 0.490s
INFO:tensorflow:{'Loss/classification_loss': 0.9208105,
 'Loss/localization_loss': 1.2354395,
 'Loss/regularization_loss': 3.0064318,
 'Loss/total_loss': 5.1626816,
 'learning_rate': 0.014666351}
I0503 10:52:17.144782 140603801323328 model_lib_v2.py:708] {'Loss/classification_loss': 0.9208105,
 'Loss/localization_loss': 1.2354395,
 'Loss/regularization_loss': 3.0064318,
 'Loss/total_loss': 5.1626816,
 'learning_rate': 0.014666351}
INFO:tensorflow:Step 200 per-step time 0.230s
I0503 10:52:40.188181 140603801323328 model_lib_v2.py:707] Step 200 per-step time 0.230s
INFO:tensorflow:{'Loss/classification_loss': 0.6854787,
 'Loss/localization_loss': 0.9672884,
 'Loss/regularization_loss': 2.972033,
 'Loss/total_loss': 4.6248,
 'learning_rate': 0.0159997}
I0503 10:52:40.188464 140603801323328 model_lib_v2.py:708] {'Loss/classification_loss': 0.6854787,
 'Loss

INFO:tensorflow:Step 1600 per-step time 0.240s
I0503 10:58:12.632241 140603801323328 model_lib_v2.py:707] Step 1600 per-step time 0.240s
INFO:tensorflow:{'Loss/classification_loss': 0.38582167,
 'Loss/localization_loss': 0.5632247,
 'Loss/regularization_loss': 2.2685077,
 'Loss/total_loss': 3.217554,
 'learning_rate': 0.034666598}
I0503 10:58:12.632453 140603801323328 model_lib_v2.py:708] {'Loss/classification_loss': 0.38582167,
 'Loss/localization_loss': 0.5632247,
 'Loss/regularization_loss': 2.2685077,
 'Loss/total_loss': 3.217554,
 'learning_rate': 0.034666598}
INFO:tensorflow:Step 1700 per-step time 0.229s
I0503 10:58:35.524143 140603801323328 model_lib_v2.py:707] Step 1700 per-step time 0.229s
INFO:tensorflow:{'Loss/classification_loss': 0.33996764,
 'Loss/localization_loss': 0.29366878,
 'Loss/regularization_loss': 2.2087088,
 'Loss/total_loss': 2.8423452,
 'learning_rate': 0.03599995}
I0503 10:58:35.524390 140603801323328 model_lib_v2.py:708] {'Loss/classification_loss': 0.3399

## Evaluating the model

In [5]:
!python model_main_tf2.py --model_dir=models/my_ssd_resnet50_v1_fpn --pipeline_config_path=models/my_ssd_resnet50_v1_fpn/pipeline.config --checkpoint_dir=models/my_ssd_resnet50_v1_fpn

2023-05-03 11:52:36.362315: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:923] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-05-03 11:52:36.369773: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:923] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-05-03 11:52:36.370925: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:923] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
W0503 11:52:36.377379 139636483225408 model_lib_v2.py:1090] Forced number of epochs for all eval validations to be 1.
INFO:tensorflow:Maybe overwriting sample_1_of_n_eval_examples: None
I0503 11:52:36.377555 139636483225408 config_util.py:552] Maybe overwriting sample_1_of_n_eval_examples: None
INFO:tensorflow:Maybe overwri

2023-05-03 11:52:43.449414: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
I0503 11:52:49.078908 139636483225408 api.py:446] feature_map_spatial_dims: [(32, 32), (16, 16), (8, 8), (4, 4), (2, 2)]
I0503 11:53:00.154425 139636483225408 api.py:446] feature_map_spatial_dims: [(32, 32), (16, 16), (8, 8), (4, 4), (2, 2)]
2023-05-03 11:53:03.521841: I tensorflow/stream_executor/cuda/cuda_dnn.cc:369] Loaded cuDNN version 8100
2023-05-03 11:53:05.891574: I tensorflow/stream_executor/cuda/cuda_blas.cc:1760] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
Instructions for updating:
Use `tf.cast` instead.
W0503 11:53:06.599727 139636483225408 deprecation.py:345] From /usr/local/lib/python3.6/dist-packages/object_detection/eval_util.py:929: to_int64 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.ca

In [6]:
# Run tensorboard within a new terminal
# !tensorboard --port 6006 --host 0.0.0.0  --logdir 'models/my_ssd_resnet50_v1_fpn'

2023-05-03 08:18:35.364822: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:923] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-05-03 08:18:35.372096: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:923] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-05-03 08:18:35.372420: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:923] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.

NOTE: Using experimental fast data loading logic. To disable, pass
    "--load_fast=false" and report issues on GitHub. More details:
    https://github.com/tensorflow/tensorboard/issues/4784

TensorBoard 2.6.0 at http://0.0.0.0:6006/ (Press CTRL+C to quit)
^C


annotations	 exporter_main_v2.py  model_main_tf2.py  pre-trained-models
exported-models  images		      models		 walkthrough.ipynb


## Exporting a trained model

In [6]:
!python exporter_main_v2.py --input_type image_tensor --pipeline_config_path models/my_ssd_resnet50_v1_fpn/pipeline.config --trained_checkpoint_dir models/my_ssd_resnet50_v1_fpn/ --output_directory exported-models/my_model

2023-05-03 12:29:27.026388: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:923] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-05-03 12:29:27.031018: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:923] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-05-03 12:29:27.031303: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:923] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-05-03 12:29:27.039409: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the app

## Inferencing

#### Load the test images

In [2]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'    # Suppress TensorFlow logging (1)
import pathlib
import tensorflow as tf

def load_images():
#     base_url = 'https://raw.githubusercontent.com/tensorflow/models/master/research/object_detection/test_images/'
    
    # Get the list of all files and directories
    path = "images/test/"
    dir_list = os.listdir(path)
    print("Files and directories in '", path, "' :")
    # prints all files
    print(dir_list)
    
    filenames = dir_list
    image_paths = []
    for filename in filenames:
#         image_path = tf.keras.utils.get_file(fname=filename,
#                                             origin=path + filename,
#                                             untar=False)
        image_path = pathlib.Path(path+filename)
        image_paths.append(str(image_path))
    return image_paths

IMAGE_PATHS = load_images()
print("Image_Paths", IMAGE_PATHS)

Files and directories in ' images/test/ ' :
['18.139572.91050.png', '18.139572.91051.png', '18.139572.91052.png', '18.139572.91053.png', '18.139572.91054.png', '18.139572.91055.png', '18.139572.91056.png', '18.139572.91057.png', '18.139572.91058.png', '18.139572.91059.png', '18.139572.91060.png', '18.139572.91061.png', '18.139572.91062.png', '18.139572.91063.png', '18.139573.91049.png', '18.139573.91050.png', '18.139573.91051.png', '18.139573.91052.png', '18.139573.91053.png', '18.139573.91054.png', '18.139573.91055.png', '18.139573.91056.png', '18.139573.91057.png', '18.139573.91058.png', '18.139573.91059.png', '18.139573.91060.png', '18.139573.91061.png', '18.139573.91062.png', '18.139573.91063.png', '18.139574.91049.png', '18.139574.91050.png', '18.139574.91051.png', '18.139574.91052.png', '18.139574.91053.png', '18.139574.91054.png', '18.139574.91055.png', '18.139574.91056.png', '18.139574.91057.png', '18.139574.91058.png', '18.139574.91059.png', '18.139574.91060.png', '18.139574.9

#### Load the model

In [3]:
import time
from object_detection.utils import label_map_util
from object_detection.utils import visualization_utils as viz_utils

PATH_TO_MODEL_DIR = "exported-models/my_model"
PATH_TO_SAVED_MODEL = PATH_TO_MODEL_DIR + "/saved_model"

print('Loading model...', end='')
start_time = time.time()

# Load saved model and build the detection function
detect_fn = tf.saved_model.load(PATH_TO_SAVED_MODEL)

end_time = time.time()
elapsed_time = end_time - start_time
print('Done! Took {} seconds'.format(elapsed_time))

Loading model...Done! Took 16.5042462348938 seconds


#### Load label map data (for plotting)

In [4]:
PATH_TO_LABELS="annotations/label_map.pbtxt"
category_index = label_map_util.create_category_index_from_labelmap(PATH_TO_LABELS,
                                                                    use_display_name=True)

#### Putting everything together

In [ ]:
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')   # Suppress Matplotlib warnings
%matplotlib inline

def load_image_into_numpy_array(path):
    """Load an image from file into a numpy array.

    Puts image into numpy array to feed into tensorflow graph.
    Note that by convention we put it into a numpy array with shape
    (height, width, channels), where channels=3 for RGB.

    Args:
      path: the file path to the image

    Returns:
      uint8 numpy array with shape (img_height, img_width, 3)
    """
    return np.array(Image.open(path))

#for all the prediction bbox without of filter, list of [N, 4]
bbox = []
# for the corresponding score of shape [N] or None.  If scores=None, then 
# this function assumes that the boxes to be plotted are groundtruth
score = []
#for the task_id 
task_id = []
#for the prediction bbox id
prediction_id = []

output_dir = "images/prediction/"
if not os.path.exists(output_dir):
      os.makedirs(output_dir)

for image_path in IMAGE_PATHS:

    print('Running inference for {}... '.format(image_path), end='')

    image_np = load_image_into_numpy_array(image_path)

    # Things to try:
    # Flip horizontally
    # image_np = np.fliplr(image_np).copy()

    # Convert image to grayscale
#     image_np = np.tile(
#         np.mean(image_np, 2, keepdims=True), (1, 1, 3)).astype(np.uint8)

    # The input needs to be a tensor, convert it using `tf.convert_to_tensor`.
    input_tensor = tf.convert_to_tensor(image_np)
#     print("input_tensor",input_tensor)
    # The model expects a batch of images, so add an axis with `tf.newaxis`.
    input_tensor = input_tensor[tf.newaxis, ...]

    # input_tensor = np.expand_dims(image_np, 0)
    detections = detect_fn(input_tensor)
    
    # All outputs are batches tensors.
    # Convert to numpy arrays, and take index [0] to remove the batch dimension.
    # We're only interested in the first num_detections.
    num_detections = int(detections.pop('num_detections'))
    detections = {key: value[0, :num_detections].numpy()
                   for key, value in detections.items()}
#     print("detections",detections)   
    
    detections['num_detections'] = num_detections

    # detection_classes should be ints.
    detections['detection_classes'] = detections['detection_classes'].astype(np.int64)
        
    image_np_with_detections = image_np.copy()

    vis_image = viz_utils.visualize_boxes_and_labels_on_image_array(
          image_np_with_detections,
          detections['detection_boxes'],
          detections['detection_classes'],
          detections['detection_scores'],
          category_index,
          use_normalized_coordinates=True,
          max_boxes_to_draw=200,
          min_score_thresh=.80,
          agnostic_mode=False)
    
    # image id
    task = os.path.splitext(os.path.basename(image_path))[0]
    output_path = output_dir + task +".png"
    
    # save prediction image
    viz_utils.save_image_array_as_png(vis_image, output_path)
    
    print("image path", image_path, output_path)
    print("boxes", detections['detection_boxes'])
    print("classes", detections['detection_classes'])
    print("scores", detections['detection_scores'])
    print("number", num_detections)
    print("image_np_with_detections", image_np_with_detections)
    

    input("Press Enter to continue...")
#     plt.figure()
#     plt.imshow(image_np_with_detections)
#     print('Done')
# plt.show()

# sphinx_gallery_thumbnail_number = 2

Running inference for images/test/18.139572.91050.png... image path images/test/18.139572.91050.png images/prediction/18.139572.91050.png
boxes [[1.73753813e-01 1.85210645e-01 3.55317831e-01 5.12954772e-01]
 [6.56852245e-01 6.55136287e-01 7.87904859e-01 7.96445072e-01]
 [1.43333077e-01 5.70587039e-01 2.77028710e-01 7.30959296e-01]
 [5.77997625e-01 2.82532245e-01 7.32589900e-01 4.05312985e-01]
 [8.91774118e-01 8.57837498e-04 9.98922765e-01 1.29232764e-01]
 [4.32483926e-02 9.32795405e-01 2.02625751e-01 9.99510884e-01]
 [6.93675518e-01 2.62632966e-06 8.44622970e-01 8.46178830e-02]
 [9.05535281e-01 3.93264860e-01 9.98632610e-01 5.23938596e-01]
 [7.83690333e-01 3.29815656e-01 9.23049808e-01 4.44277197e-01]
 [2.77526677e-03 8.12161267e-02 1.89579949e-01 3.49461347e-01]
 [8.70759130e-01 4.86990303e-01 9.87232089e-01 6.23050511e-01]
 [5.90804994e-01 5.84146678e-01 6.91590488e-01 6.80894673e-01]
 [5.31742752e-01 9.36103761e-01 6.67369306e-01 9.99860585e-01]
 [8.84130716e-01 8.18789363e-01 9.785

Press Enter to continue...
Running inference for images/test/18.139572.91051.png... image path images/test/18.139572.91051.png images/prediction/18.139572.91051.png
boxes [[4.74697128e-02 3.89800519e-01 2.28457093e-01 5.61593771e-01]
 [3.86072844e-01 8.90152812e-01 5.37905693e-01 9.99751091e-01]
 [2.24637508e-01 0.00000000e+00 4.57236707e-01 2.60202587e-01]
 [2.09212303e-01 8.37468565e-01 3.48593056e-01 9.99882877e-01]
 [1.75049543e-01 8.24792027e-01 3.15032691e-01 9.90143061e-01]
 [2.76764892e-02 8.37340891e-01 1.33202732e-01 9.69267428e-01]
 [5.98187923e-01 9.94852930e-03 8.58736157e-01 2.41443038e-01]
 [4.14621830e-01 7.35539943e-02 6.98500872e-01 4.24016416e-01]
 [8.08324337e-01 1.68454096e-01 9.97128010e-01 4.24971402e-01]
 [2.80734152e-03 8.21658492e-01 1.00006402e-01 9.49540496e-01]
 [0.00000000e+00 6.16742253e-01 7.37502351e-02 7.48591900e-01]
 [1.21758759e-01 8.90450895e-01 1.94302619e-01 9.73249376e-01]
 [7.01084137e-01 9.81036663e-01 8.40687752e-01 9.98935342e-01]
 [6.022416